language: python

python:
  - "3.6"

cache: pip

services:
  - postgresql

addons:
  apt:
    packages:
      - sshpass
  postgresql: '14.1'

env:
  QPC_DBMS=postgres
  QPC_DBMS_DATABASE=postgres
  QPC_DBMS_PORT=5432
  QPC_DBMS_USER=postgres
  QPC_DBMS_PASSWORD=password
  QPC_DBMS_HOST=127.0.0.1
  PYTHONHASHSEED=0

# command to install dependencies
install:
  - pip install -U pip
  - pip install -r dev-requirements.txt
  - pip install codecov
  - nvm install node
  - npm install swagger-cli

# command to run tests
script:
  - make lint
  - make server-init
  - make test-coverage
  - make swagger-valid

after_success:
  - codecov

notifications:
  slack:
    secure: SSlalMN72w3gghu0RRTEznrdVgFCSCLheutRp9O9W82LVaz4K7xu9Qel7pRghgoiafS2nBufaGXrmk6mj4InNhJfc0hwLpa9kZcntD8kuap5qJC4A5Qvx1gq+70DjVbaVbBfrAl1Bsu+dkR6SfuCV9sWTFjUfnCt5H1ugprQXe0utLt7P//ZELOWVghyiFBIr+kOrUCfDV0HecTHOxQIFlxZpB2Y0QGYXUwtljhVFaMcCQLHvOhQelIellrRjSUURQOo9TLw8NQUdJHWxnKqAXl2VNG9CCRKJoH6i1sGi53gWou+EeKXM6ERCgO4mgzDyrPJe644Q7e6Gt6Htz1Oc22n0ghR4CE62B44bzhtViCmpptmgMIFLJfEg+zq0ZQzdxSx6dblkT0hC/dVwPLyjUFffojYPnarx9rvmM56yq3FS++2nbSg2JLvscHCDYqbivykdgz80VujxfYKSOtHTirteNDbKinx1DtibBhl0GNeRE0xM/OEPgLyD1eQbak7Dfr9rwebO2sSxplvH5CNn16jarpnqC+2x47leNOxjba2Je/fN01tIcHKQzgVn7TI/jfek+CJpqdgU2eXpz0g18PnPjMpdfZefdW2V/HTA7ucCJyoDEuouI54AtzvW3Oi9kJ81kesutNBl1zyCjiGrL9ynyDS9xPmPbJCWTTXw9A=
