---

- name: Test for chkconfig command
  shell: command -v chkconfig
  register: have_chkconfig_raw
  ignore_errors: yes

- name: Set have_chkconfig
  set_fact:
    have_chkconfig: "{{ have_chkconfig_raw.rc == 0 }}"

- name: Test for docker command
  shell: command -v docker
  register: have_docker_raw
  ignore_errors: yes

- name: Set have_docker
  set_fact:
    have_docker: "{{ have_docker_raw.rc == 0 }}"

- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: present

- name: Install lvm2
  yum:
    name: lvm2
    state: present

- name: Find installable local epel rpm
  find:
    paths: "{{ pkg_install_dir }}"
    patterns: 'docker*.rpm'
  register: find_docker_rpm_local_raw
  when: not have_docker

- name: Set find_docker_rpm_local
  set_fact:
    find_docker_rpm_local: "{{ find_docker_rpm_local_raw['matched'] == 1 }}"
  when: "find_docker_rpm_local_raw is defined and 'matched' in find_docker_rpm_local_raw"

- name: Set find_docker_rpm_local_path
  set_fact:
    find_docker_rpm_local_path: "{{ find_docker_rpm_local_raw['files'][0]['path'] }}"
  when: find_docker_rpm_local is defined and find_docker_rpm_local

- name: Install Docker from local path
  shell: rpm -Uvh --force "{{find_docker_rpm_local_path}}"
  # ignore_errors: yes
  when: not have_docker

- name: Add Docker CE repository for Centos/RHEL 7 family
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  when: is_rhel7 and not have_docker and not find_docker_rpm_local

- name: Install the latest version of docker-ce
  yum:
    name: docker-ce
    state: latest
  when: not have_docker and not find_docker_rpm_local

- name: Obtain Docker Engine for Centos/RHEL 6 family
  get_url:
    url: https://yum.dockerproject.org/repo/main/centos/6/Packages/docker-engine-1.7.1-1.el6.x86_64.rpm
    dest: "{{ pkg_install_dir }}"
    mode: 0644
  when: is_rhel6 and not have_docker and not find_docker_rpm_local

- name: Find installable local epel rpm
  find:
    paths: "{{ pkg_install_dir }}"
    patterns: 'docker*.rpm'
  register: find_docker_rpm_local_raw
  when: is_rhel6 and not have_docker

- name: Set find_docker_rpm_local
  set_fact:
    find_docker_rpm_local: "{{ find_docker_rpm_local_raw['matched'] == 1 }}"
  when: "find_docker_rpm_local_raw is defined and 'matched' in find_docker_rpm_local_raw"

- name: Set find_docker_rpm_local_path
  set_fact:
    find_docker_rpm_local_path: "{{ find_docker_rpm_local_raw['files'][0]['path'] }}"
  when: find_docker_rpm_local is defined and find_docker_rpm_local

- name: Install Docker from local path
  shell: rpm -Uvh --force "{{find_docker_rpm_local_path}}"
  when: is_rhel6 and not have_docker

- name: Start Docker
  service:
    name: docker
    state: started

- name: Setup chkconfig to start docker
  shell: chkconfig docker on
  ignore_errors: yes
  when: is_rhel6 and have_chkconfig
