---

- name: Test for chkconfig command
  shell: command -v chkconfig
  register: have_chkconfig_raw
  ignore_errors: yes

- name: Set have_chkconfig
  set_fact:
    have_chkconfig: "{{ have_chkconfig_raw.rc == 0 }}"

- name: Test for systemctl command
  shell: command -v systemctl
  register: have_systemctl_raw
  ignore_errors: yes

- name: Set have_systemctl
  set_fact:
    have_systemctl: "{{ have_systemctl_raw.rc == 0 }}"

- name: Test for docker command
  shell: command -v docker
  register: have_docker_raw
  ignore_errors: yes

- name: Set have_docker
  set_fact:
    have_docker: "{{ have_docker_raw.rc == 0 }}"

- name: Install yum-utils (RHEL/Centos)
  yum:
    name: yum-utils
    state: present
  become: true
  when:
    - not have_docker

- name: Install device-mapper-persistent-data (RHEL/Centos)
  yum:
    name: device-mapper-persistent-data
    state: present
  become: true
  when:
    - not have_docker

- name: Install lvm2 (RHEL/Centos)
  yum:
    name: lvm2
    state: present
  become: true
  when:
    - not have_docker

- name: Install libcgroup (RHEL 6)
  yum:
    name: libcgroup
    state: present
  become: true
  when:
    - is_rhel_centos_6
    - not have_docker

- name: Install xz (RHEL 6)
  yum:
    name: xz
    state: present
  become: true
  when:
    - is_rhel_centos_6
    - not have_docker

- name: Install libselinux-python (RHEL/Centos 6)
  yum:
    name: libselinux-python
    state: present
  become: true
  when:
    - is_rhel_centos_6
    - selinux_on
    - ansible_selinux_python_present is defined and ansible_selinux_python_present == false
    - not have_docker

- name: Find installable local epel rpm
  find:
    paths: "{{ pkg_install_dir }}"
    patterns: 'docker*.rpm'
  register: find_docker_rpm_local_raw
  when:
    - not have_docker

- name: Set find_docker_rpm_local
  set_fact:
    find_docker_rpm_local: "{{ find_docker_rpm_local_raw['matched'] == 1 }}"
  when:
    - find_docker_rpm_local_raw is defined
    - "'matched' in find_docker_rpm_local_raw"

- name: Set find_docker_rpm_local_path
  set_fact:
    find_docker_rpm_local_path: "{{ find_docker_rpm_local_raw['files'][0]['path'] }}"
  when:
    - find_docker_rpm_local is defined
    - find_docker_rpm_local

- name: Install Docker from local path
  shell: rpm -Uvh --force "{{find_docker_rpm_local_path}}"
  become: true
  when:
    - not have_docker
    - find_docker_rpm_local

- name: Add Docker CE repository (Centos 7)
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
  become: true
  when:
    - is_centos_7
    - not have_docker
    - not find_docker_rpm_local

- name: Install the latest version of docker (RHEL 7)
  yum:
    name: docker
    state: latest
  become: true
  when:
    - is_rhel7
    - not have_docker
    - not find_docker_rpm_local

- name: Install the latest version of docker-ce (Centos 7)
  yum:
    name: docker-ce
    state: latest
  become: true
  when:
    - is_centos_7
    - not have_docker
    - not find_docker_rpm_local

- name: Ensure packages directory exists
  shell: mkdir -p "{{ pkg_install_dir }}"
  when:
    - is_rhel_centos_6
    - not have_docker
    - not find_docker_rpm_local

- name: Obtain Docker Engine for (Centos/RHEL 6)
  get_url:
    url: http://yum.dockerproject.org/repo/main/centos/6/Packages/docker-engine-1.7.1-1.el6.x86_64.rpm
    dest: "{{ pkg_install_dir }}"
    mode: 0644
  when:
    - is_rhel_centos_6
    - not have_docker
    - not find_docker_rpm_local

- name: Find installable local epel rpm (RHEL/Centos 6)
  find:
    paths: "{{ pkg_install_dir }}"
    patterns: 'docker*.rpm'
  register: find_docker_rpm_local_raw
  when:
    - is_rhel_centos_6
    - not have_docker

- name: Set find_docker_rpm_local
  set_fact:
    find_docker_rpm_local: "{{ find_docker_rpm_local_raw['matched'] == 1 }}"
  when:
    - find_docker_rpm_local_raw is defined
    - "'matched' in find_docker_rpm_local_raw"

- name: Set find_docker_rpm_local_path
  set_fact:
    find_docker_rpm_local_path: "{{ find_docker_rpm_local_raw['files'][0]['path'] }}"
  when:
    - find_docker_rpm_local is defined
    - find_docker_rpm_local

- name: Install Docker from local path (RHEL/Centos 6)
  shell: rpm -Uvh --force "{{find_docker_rpm_local_path}}"
  become: true
  when:
    - is_rhel_centos_6
    - not have_docker

- name: Start Docker
  service:
    name: docker
    state: started
  become: true

- name: Setup chkconfig to start docker (RHEL/Centos 6)
  shell: chkconfig docker on
  become: true
  ignore_errors: yes
  when:
    - is_rhel_centos_6
    - have_chkconfig

- name: Setup systemctl to start docker (RHEL/Centos 7)
  shell: systemctl enable docker
  become: true
  ignore_errors: yes
  when:
    - is_rhel_centos_7
    - have_systemctl
